# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1bcf0e42f931f8ea29d2aed36a83d312d9d5161fd35a20aaf4ab1b83b465b1c5d559f673011bbaab741080392e2b5ad6628f4bf1caa62ee30cf255ea5308c80

test:
  secret_key_base: 5312827e6f7677b52e4140920499ba8f2c5ea735612440733c959c1b0df39efec0618de2451280272b37137f7d44786551ea1009a2777357b80116dad43b7a2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
